# Generated by Django 3.2 on 2023-10-14 10:09

from django.db import migrations, models
import django_spanner


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DivisionModel',
            fields=[
                ('id', models.AutoField(default=django_spanner.gen_rand_int64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'divisions',
            },
        ),
    ]
