# Generated by Django 3.2 on 2023-10-14 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20231014_0746'),
        ('division', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Division',
            new_name='DivisionModel',
        ),
    ]
