# Generated by Django 3.2 on 2023-10-14 10:09

from django.db import migrations, models
import django.db.models.deletion
import django_spanner


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('division', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('id', models.AutoField(default=django_spanner.gen_rand_int64, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('surpervisor_employee_id', models.IntegerField(null=True)),
                ('is_supervisor', models.BooleanField(default=False)),
                ('position_name', models.CharField(default='intern', max_length=255)),
                ('division_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='division.divisionmodel')),
            ],
            options={
                'db_table': 'employees',
            },
        ),
    ]
