# Generated by Django 3.2 on 2023-10-14 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemodel',
            name='is_supervisor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeemodel',
            name='surpervisor_employee_id',
            field=models.IntegerField(null=True),
        ),
    ]
