# Generated by Django 3.2 on 2023-10-14 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('division', '0002_rename_division_divisionmodel'),
        ('employee', '0002_auto_20231014_0746'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemodel',
            name='division_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='division.divisionmodel'),
            preserve_default=False,
        ),
    ]
