# Generated by Django 3.2 on 2023-10-14 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_auto_20231014_0904'),
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Plans',
            new_name='PlanModel',
        ),
    ]
